DATA TRIAL;
	INFILE 'C:\대학원\2018-2\1. 전공\임상시험자료분석2\L2-자료분석 I data\EX3-1.CSV' DELIMITER=',' FIRSTOBS=2;
	INPUT TRT $	 CENTER	PAT	SEX $	AGE	SCORE @@;
RUN;

/*1.4*/
PROC TTEST H0=20 DATA=TRIAL;
	VAR SCORE;
RUN;

/*2.1*/
PROC SORT DATA = TRIAL; BY TRT;

PROC GLM DATA = TRIAL;
	CLASS TRT SEX;
	MODEL SCORE = TRT;
	MEANS TRT/T DUNNETT;
RUN;

/*2.2*/
PROC SORT DATA = TRIAL;
	BY TRT CENTER;

PROC MEANS MEAN STD N;
	VAR SCORE;
	BY TRT CENTER;
RUN;

PROC GLM DATA = TRIAL;
	CLASS TRT SEX;
	MODEL SCORE = TRT CENTER TRT*CENTER;
	MEANS TRT / T;
	LSMEANS TRT / PDIFF STDERR;
RUN;

/*2.3*/
PROC GLM DATA = TRIAL;
	CLASS TRT SEX;
	MODEL SCORE = TRT CENTER ;
	MEANS TRT / T;
	LSMEANS TRT / PDIFF STDERR;
RUN;
