DATA DOGS;
	INFILE 'C:\대학원\2018-2\1. 전공\임상시험자료분석2\과제/sleeping-dog.CSV' DELIMITER=',' FIRSTOBS=2;
	INPUT Dog TRT1 TRT2 TRT3 TRT4;
RUN;

DATA hw4; SET DOGS;
	KEEP Dog TRT RES;
	RES = TRT1; TRT='TRT1'; OUTPUT;
 	RES = TRT2; TRT='TRT2'; OUTPUT;
 	RES = TRT3; TRT='TRT3'; OUTPUT;
 	RES = TRT4; TRT='TRT4'; OUTPUT;
RUN;

PROC PRINT DATA=hw4;
	VAR Dog TRT RES;
RUN;

PROC SORT DATA=hw4; BY TRT;
PROC MEANS MEAN STD N DATA = hw4;
	BY TRT;
	VAR RES;
RUN;

/*One Way ANOVA*/
PROC GLM DATA=hw4;
	CLASS Dog TRT;
	MODEL RES = TRT;
	MEANS TRT/T DUNNETT;
RUN;

/*Repeated Measure ANOVA(의미X)*/
PROC GLM DATA=hw4;
	CLASS Dog TRT;
	MODEL RES = TRT;
	RANDOM Dog(TRT);
	TEST H=TRT E=Dog(TRT);
	QUIT;
RUN;


