DATA TRIAL;
	INFILE 'C:\대학원\2018-2\1. 전공\임상시험자료분석2\과제/trial.CSV' DELIMITER=',' FIRSTOBS=2;
	INPUT TRT $ CENTER $ PAT  SEX $  AGE  SCORE;
RUN;

PROC SORT DATA = TRIAL; BY TRT SEX;
PROC PRINT DATA = TRIAL;
	VAR TRT CENTER SEX AGE SCORE;
RUN;

PROC MEANS MEAN STD N DATA = TRIAL;
	BY TRT SEX;
	VAR SCORE;
RUN;

/*1번*/
PROC REG CORR DATA = TRIAL;
	MODEL SCORE = AGE;
RUN;

/*2번*/
PROC GLM DATA = TRIAL;
	CLASS TRT CENTER SEX;
	MODEL  SCORE = AGE TRT/ SOLUTION;
	LSMEANS TRT/PDIFF STDERR;
RUN;

/*3번*/
PROC GLM DATA = TRIAL;
	CLASS TRT CENTER SEX;
	MODEL  SCORE = AGE TRT AGE*TRT;
RUN;

/*4번*/
PROC GLM DATA = TRIAL;
	CLASS TRT CENTER SEX;
	MODEL  SCORE = AGE CENTER TRT/ SOLUTION;
	LSMEANS TRT/PDIFF STDERR;
RUN;


